services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dados_db:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"    # Porta do protocolo AMQP
      - "15672:15672"  # Porta do Painel de Gerenciamento Web
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mysql
    ports:
      - 8082:8080
volumes:
  dados_db:
# lembrar:
#docker-compose up -d - ReInicia o conteineres;
#docker-compose down - Para os conteineres.